site_name: Aman's Coding Notes
site_description: "My personal knowledge base of programming and web development."
site_author: Aman Verma
repo_url: https://github.com/amanverma2009/coding-notes
repo_name: coding-notes

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.action.edit

plugins:
  - search
  - tags
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.inlinehilite
